### PR TITLE
[#14] Removed all other non-specified keys from the authorized_keys file

### LINKED ISSUE #14: [ssh] The SSH playbook should remove keys that are _not_ on the list

### PR DESCRIPTION
**Pull request by kamilongus**
Fixes: https://github.com/aelve/ops/issues/14

### CODE REVIEW

**Comment by neongreen** [comment]
This doesn't work if a person has more than one SSH key (e.g. https://github.com/lorof.keys). I looked at the resulting `authorized_keys` file and found a line with two keys, while it should be two lines instead:

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCB2iZxKWRUslwfN4LcWHRCryv3/Fqe/LS8kzKyNp1kXCtWLvw6OqRlAO9Pw8BwqnP6H9SdiGR9jk20968bvm9Mnah54j4r+NA89nTijE1kjpIpu9yyByPsxroLjKI6bEdDdJapVOAVLm6mdhEzjpgYAWuXHSdVQ+l083uEyrpJ+ChhfhFi52rLoySp+YowghrfVuUE8vVaZnuWkQtrbDbTl1/nOxROU/4QfOskEiupaz+l9ERiyLKU2yKKkyM/2+/AJFr9Bzbclh0WsCQ2x9aUa8biGjSHyswWN4hQ9/uOUGIyLnMh8u9B4vmck/Uj65PwlLLX3D9zt0guJRNspzed,ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCogEDIB5MkE2f4jLzGPuesSfSEuh0Ce69IogP8WWAF+q5DAqMbSB1ZlSVp9QsO9n6ctiyU4pEmf4zWsngRNc8erunxSrxe5DL5cEKFBo+hqL0Sq2xO3xRL/dwpl2iYzdeL5AcphHN8StS3fDNbMNEQg5wjo5x2wGtmBjdxb88sgmFn5hsVVOXy9li18e4OHXGACSabDrMGglH+Y8nZcdpQ7Q/cF7RNZvjmhDRko1rrR/PjkAqaUjjX2SLHTQUm8yJUvDp9QYLfqaK070kIRqBdDbKGmcV7PAjAqagPpDIE9r3/YRvo+eUww/JOW42aobWTHaExNf/cLim9sM35gjm6GKwXgYZ9kNZBzK8pGHWFi7SJf7oXJTZmxAswkURXOS/gYkwM9VfS2AVitrrVzYVuVaSmCi5yA5l6oNCiuxFZ9Kcho1gppb7vpxbgyCWOXP13JuZ/VwdvaARW6I2vYEmaFdblvSxUOzNKp56TPThLfx3rU/VIIzJCDH+aza1tBl3DyGu1kK7NFYLny2MhAWKt2jQORXcJvd3+sjLpbDY6GfO55e9/wOHKyBodCORAJLaStso+6txRzML6OGjlNCvY11fnj5lEqeozwFpRGYdBpuCXTTTmzsu7G6pnCfZo8Isni6+3H5x6Zqs2gQ1ljBYTVMMfSQRoo3SijRM3IdSn1Q==`

**Comment by kamilongus** [comment]
@neongreen please check it again

**Comment by neongreen** [comment]
I used `wantlist=true` instead – it seemed more robust (e.g. what if SSH keys somehow contain commas?).

```
ssh_keys_list: "{{ (ssh_keys_list | default([]) | list) + lookup('url', item, wantlist=true) }}"
```

**Review by neongreen — APPROVED** [review]

**Review by neongreen — CHANGES_REQUESTED** [review]
Actually, it's still broken a bit – it collects each key as many times as there are `hosts`. I will fix it.

**Review by neongreen — APPROVED** [review]

**Comment by neongreen** [comment]
This playbook has been applied to all hosts.

**Pull request merged**
